spring:
  application:
    name: schemas
  kafka:
    properties:
      schema.registry.url: http://localhost:8081
    producer:
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        specific.avro.reader: true
        spring.deserializer.value.delegate.class: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
        spring.deserializer.value.function: "com.example.schemas.kafka.Consumer.FailedDeserializationFunction"